# -*- coding: utf-8 -*-
"""suc_CAG_GPU.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U1qaaQq13dJ9OGI0pKL8fRkb54SGkUEV
"""







"""https://github.com/hhhuang/CAG"""

!git clone https://github.com/hhhuang/CAG.git

# Commented out IPython magic to ensure Python compatibility.
# %cd CAG

!pip install -r ./requirements.txt

!cp /content/CAG/.env.template /content/CAG/.env

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/CAG
!sh ./downloads.sh

!python ./kvcache.py --kvcache file --dataset "squad-train" --similarity bertscore \
    --maxKnowledge 5 --maxParagraph 100 --maxQuestion 1000  \
    --modelname "meta-llama/Llama-3.2-1B-Instruct" --randomSeed 0 \
    --output "./result_kvcache.txt"

import torch
import torchvision

print(f"Torch version: {torch.__version__}")
print(f"Torchvision version: {torchvision.__version__}")

!pip install torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1 --index-url https://download.pytorch.org/whl/cu124
# CPU only

!python ./kvcache.py -h

!pip install torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1 --index-url https://download.pytorch.org/whl/cpu

!pip uninstall torch torchvision torchaudio



# Commented out IPython magic to ensure Python compatibility.
# %cd /content/CAG
!python ./kvcache.py --kvcache file --dataset "squad-train" --similarity bertscore \
    --maxKnowledge 1 --maxParagraph 1 --maxQuestion 1 \
    --modelname "meta-llama/Llama-3.2-1B-Instruct" --randomSeed 0 \
    --output "./result_kvcache.txt"

/content/CAG/result_kvcache.txt

KVcache prepared in 0.7992591857910156 seconds
[0]: Semantic Similarity: 0.09896,	 cache time: 7.152557373046875e-07,	 generate time: 0.13470172882080078
[0]: [Cumulative]: Semantic Similarity: 0.09896,	 cache time: 7.152557373046875e-07,	 generate time: 0.13470172882080078

Result for ./result_kvcache.txt
Prepare time: 0.7992591857910156
Average Semantic Similarity: 0.0989607721567154
cache time: 7.152557373046875e-07,	 generate time: 0.13470172882080078

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/CAG
!python ./kvcache.py --kvcache file --dataset "squad-train" --similarity bertscore \
    --maxKnowledge 5 --maxParagraph 100 --maxQuestion 1000  \
    --modelname "meta-llama/Llama-3.2-1B-Instruct" --randomSeed 0 \
    --output "./result_kvcache.txt"

!python ./kvcache.py --kvcache file --dataset "squad-train" --similarity bertscore \
    --maxKnowledge 5 --maxParagraph 100 --maxQuestion 1000  \
    --modelname "meta-llama/Llama-3.1-8B-Instruct" --randomSeed 0 \
    --output "./result_kvcache.txt"